version: '3.7'

networks:
  transcendence: {}

services:
  server:
    image: nginx
    container_name: transcendence-nginx-prod
    restart: always
    depends_on:
      - frontend
    volumes:
      - './nginx/conf.d/production.conf:/etc/nginx/conf.d/default.conf'
      - './frontend/dist:/var/www/html'
    env_file:
      - ./env/.frontend.env
    ports:
      - '4443:443'
      - '8880:80'
    networks:
      - transcendence

  frontend:
    image: trans-frontend-prod
    container_name: transcendence-frontend-prod
    restart: "no"
    build:
      context: ./frontend
      target: prod
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    depends_on:
      - backend
    env_file:
      - ./env/.frontend.env
    volumes:
      - './frontend/dist:/app/dist'
      - 'frontend_modules:/app/node_modules'
    expose:
      - '8000'
    networks:
      - transcendence

  backend:
    image: trans-backend-prod
    container_name: transcendence-backend-prod
    restart: always
    build:
      context: ./backend
      target: prod
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    depends_on:
      - db
    env_file:
      - ./env/.backend.env
    volumes:
      - "./uploads:/server/uploads"
    expose:
      - '3080'
    networks:
      - transcendence

  adminer:
    image: adminer
    container_name: transcendence-adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - '8080:8080'
    networks:
      - transcendence

  db:
    image: postgres:15.1-alpine
    container_name: transcendence-db
    restart: always
    env_file:
      - ./env/.postgres.env
    volumes:
      - 'data:/var/lib/postgresql/data'
    expose:
      - '5432'
    networks:
      - transcendence

volumes:
  data:
  frontend_modules:
  backend_modules:
