version: '3.7'

networks:
  transcendence: {}

services:
  frontend:
    image: frontend
    container_name: my-app
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '8000:8000'
    depends_on:
      - backend

  backend:
    image: backend
    container_name: my-server
    build:
      context: ./backend
      target: dev
    networks:
      - transcendence
    env_file:
      - ./env/.backend_env
    volumes:
      - './backend:/server'
      - '/server/node_modules'
    ports:
      - '3080:3080'
    depends_on:
      - db

  adminer:
    image: adminer
    container_name: my-adminer
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - transcendence

  db:
    image: postgres:15.1-alpine
    container_name: my-db
    restart: on-failure
    networks:
      - transcendence
    env_file:
      - ./env/.postgres_env
    volumes:
      - 'data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

volumes:
  data: