version: '3.7'

services:
  frontend:
    image: frontend
    container_name: my-app
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'

  backend:
    image: backend
    container_name: my-server
    build: ./backend
    volumes:
      - './backend:/server'
      - '/server/node_modules'
    ports:
      - '3080:3080'