version: '3.7'

networks:
  transcendence: {}

services:

  transcendence:
    image: transcendence-full
    container_name: transcendence
    restart: always
    build:
      context: .
      target: prod
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - "./uploads:/server/uploads"
    ports:
      - '3080:3080'
    networks:
      - transcendence

  db:
    image: postgres:15.1-alpine
    container_name: transcendence-db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - 'data:/var/lib/postgresql/data'
    expose:
      - '5432'
    networks:
      - transcendence

volumes:
  data:
  frontend_modules:
  backend_modules:
