version: '3.7'

networks:
  backend: {}

services:
  frontend:
    image: frontend
    container_name: my-app
    build: ./frontend
    volumes:
      - './frontend:/app'
    ports:
      - '8080:8080'
    depends_on:
      - backend

  backend:
    image: backend
    container_name: my-server
    build:
      context: ./backend
      target: dev
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - './backend:/server'
    ports:
      - '3080:3080'
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    restart: always
    networks:
      - backend
    env_file:
      - .env
    ports:
      - '5050:80'
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    container_name: my-db
    restart: always
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - 'data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

volumes:
  data: