version: '3.7'

services:
  my-app:
    image: node-front
    container_name: my-app
    build: ./app
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'

  backend:
    image: node-back
    container_name: my-server
    build: ./backend
    volumes:
      - './backend:/server'
      - '/server/node_modules'
    ports:
      - '3080:3080'
