version: '3.7'

networks:
  transcendence: {}

services:
  server:
    image: trans-nginx
    build:
      context: ./nginx
      target: dev
    container_name: transcendence-server
    restart: always
    depends_on:
      - frontend
    volumes:
      - './nginx/conf.d/development.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '4443:443'
      - '8880:80'
    networks:
      - transcendence

  frontend:
    image: trans-frontend
    container_name: transcendence-frontend
    restart: always
    build:
      context: ./frontend
      target: dev
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    depends_on:
      - backend
    environment:
      - VITE_APP_URL=${FRONTEND_URL}
      - VITE_BACKEND_URL=${BACKEND_URL}
      - VITE_JWT_COOKIE=${JWT_COOKIE}
      - VITE_FORTYTWO_API_UID=${FORTYTWO_API_UID}
    volumes:
      - './frontend:/app'
      - 'frontend_modules:/app/node_modules'
    expose:
      - '8000'
    networks:
      - transcendence

  backend:
    image: trans-backend
    container_name: transcendence-backend
    restart: always
    build:
      context: ./backend
      target: dev
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    depends_on:
      - db
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_COOKIE=${JWT_COOKIE}
      - JWT_KEY=${JWT_KEY}
      - FORTYTWO_API_UID=${FORTYTWO_API_UID}
      - FORTYTWO_API_SECRET=${FORTYTWO_API_SECRET}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - './backend:/server'
      - 'backend_modules:/server/node_modules'
    expose:
      - '3080'
    networks:
      - transcendence

  adminer:
    image: adminer
    container_name: transcendence-adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - '8080:8080'
    networks:
      - transcendence

  db:
    image: postgres:15.1-alpine
    container_name: transcendence-db
    restart: always
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - 'data:/var/lib/postgresql/data'
    expose:
      - '5432'
    networks:
      - transcendence

volumes:
  data:
  frontend_modules:
  backend_modules:
