name: "commits-checks"

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  commits-checks:

    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
    - name: "Check out the repository"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: "Check commit messages"
      uses: docker://aevea/commitsar
