# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: setup backend
      run: yarn install
      working-directory: backend
    - name: build backend
      run: yarn build
      working-directory: backend
    # - name: test backend
    #   run: yarn test
    #   working-directory: backend
    - name: setup frontend
      run: yarn install
      working-directory: frontend
    - name: build frontend
      run: yarn build-only # TODO: change to build when all errors are fixed
      working-directory: frontend
    # - name: test frontend
    #   run: yarn test
    #   working-directory: frontend
